import type { DesignTokens } from '@franken-ui/core';

/**
 * Generate theme.css from design tokens
 */
export function generateThemeCSS(tokens: DesignTokens): string {
    const fontFamily = tokens.fonts.heading.split(',')[0].trim().replace(/\s+/g, '+');

    return `/* Generated by Franken-UI */
@import url('https://fonts.googleapis.com/css2?family=${fontFamily}:wght@400;500;600;700&display=swap');

:root {
  /* Shape */
  --radius: ${tokens.radius};
  
  /* Typography */
  --font-heading: ${tokens.fonts.heading};
  --font-body: ${tokens.fonts.body};
  --font-mono: ${tokens.fonts.mono};
  
  /* Light Mode Colors */
  --background: ${tokens.colors.background};
  --foreground: ${tokens.colors.foreground};
  --card: ${tokens.colors.card};
  --card-foreground: ${tokens.colors.cardForeground};
  --popover: ${tokens.colors.popover};
  --popover-foreground: ${tokens.colors.popoverForeground};
  --primary: ${tokens.colors.primary};
  --primary-foreground: ${tokens.colors.primaryForeground};
  --secondary: ${tokens.colors.secondary};
  --secondary-foreground: ${tokens.colors.secondaryForeground};
  --muted: ${tokens.colors.muted};
  --muted-foreground: ${tokens.colors.mutedForeground};
  --accent: ${tokens.colors.accent};
  --accent-foreground: ${tokens.colors.accentForeground};
  --destructive: ${tokens.colors.destructive};
  --destructive-foreground: ${tokens.colors.destructiveForeground};
  --border: ${tokens.colors.border};
  --input: ${tokens.colors.input};
  --ring: ${tokens.colors.ring};
${tokens.colors.chart1 ? `  --chart-1: ${tokens.colors.chart1};` : ''}
${tokens.colors.chart2 ? `  --chart-2: ${tokens.colors.chart2};` : ''}
${tokens.colors.chart3 ? `  --chart-3: ${tokens.colors.chart3};` : ''}
${tokens.colors.chart4 ? `  --chart-4: ${tokens.colors.chart4};` : ''}
${tokens.colors.chart5 ? `  --chart-5: ${tokens.colors.chart5};` : ''}
}

.dark {
  --background: ${tokens.darkColors.background};
  --foreground: ${tokens.darkColors.foreground};
${tokens.darkColors.card ? `  --card: ${tokens.darkColors.card};` : ''}
${tokens.darkColors.cardForeground ? `  --card-foreground: ${tokens.darkColors.cardForeground};` : ''}
${tokens.darkColors.popover ? `  --popover: ${tokens.darkColors.popover};` : ''}
${tokens.darkColors.popoverForeground ? `  --popover-foreground: ${tokens.darkColors.popoverForeground};` : ''}
${tokens.darkColors.primary ? `  --primary: ${tokens.darkColors.primary};` : ''}
${tokens.darkColors.primaryForeground ? `  --primary-foreground: ${tokens.darkColors.primaryForeground};` : ''}
${tokens.darkColors.secondary ? `  --secondary: ${tokens.darkColors.secondary};` : ''}
${tokens.darkColors.secondaryForeground ? `  --secondary-foreground: ${tokens.darkColors.secondaryForeground};` : ''}
${tokens.darkColors.muted ? `  --muted: ${tokens.darkColors.muted};` : ''}
${tokens.darkColors.mutedForeground ? `  --muted-foreground: ${tokens.darkColors.mutedForeground};` : ''}
${tokens.darkColors.accent ? `  --accent: ${tokens.darkColors.accent};` : ''}
${tokens.darkColors.accentForeground ? `  --accent-foreground: ${tokens.darkColors.accentForeground};` : ''}
${tokens.darkColors.destructive ? `  --destructive: ${tokens.darkColors.destructive};` : ''}
${tokens.darkColors.border ? `  --border: ${tokens.darkColors.border};` : ''}
${tokens.darkColors.input ? `  --input: ${tokens.darkColors.input};` : ''}
${tokens.darkColors.ring ? `  --ring: ${tokens.darkColors.ring};` : ''}
}
`;
}

/**
 * Generate animations.css from animation definitions
 */
export function generateAnimationsCSS(animations: { name: string; definition: string }[]): string {
    const keyframes = animations
        .filter(a => typeof a.definition === 'string')
        .map(a => a.definition)
        .join('\n\n');

    return `/* Generated Animations - Franken-UI */
${keyframes}
`;
}
